# Generated by Django 4.1.1 on 2022-12-03 19:02

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.department')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField()),
                ('iin_num', models.IntegerField(unique=True)),
                ('id_num', models.IntegerField(unique=True)),
                ('blood_group', models.CharField(choices=[('A', 'Group A'), ('B', 'Group B'), ('O', 'Group O'), ('AB', 'Group AB')], max_length=2)),
                ('emergency_cont_num', models.CharField(max_length=15)),
                ('contact_num', models.CharField(max_length=15, unique=True)),
                ('address', models.CharField(max_length=150)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=7)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField()),
                ('iin_num', models.IntegerField(unique=True)),
                ('id_num', models.IntegerField(primary_key=True, serialize=False)),
                ('spec_details_id', models.IntegerField(unique=True)),
                ('experience', models.IntegerField()),
                ('photo', models.ImageField(upload_to='')),
                ('category', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('start_hours', models.TimeField(default=datetime.time(8, 0))),
                ('end_hours', models.TimeField(default=datetime.time(21, 0))),
                ('degree', models.CharField(choices=[('ASD', 'Associate Degree'), ('BA', "Bachelor's Degree"), ('MD', "Master's Degree"), ('PhD', 'Doctoral Degree')], max_length=3)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('address', models.CharField(max_length=150)),
                ('homepage_url', models.URLField(blank=True, null=True)),
                ('department', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hospital.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('day', models.DateField()),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('doctor_id', 'day', 'time'), name='unique_constraint_appointment'),
        ),
    ]
